services:
  postgres:
    image: postgres:16
    container_name: moneyharbor-postgres
    environment:
      POSTGRES_DB: moneyharbor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 1s
      timeout: 3s
      retries: 20
    labels:
      org.springframework.boot.service-connection: postgres
volumes:
  pg_data: