import com.jayway.jsonpath.JsonPath;
import com.kavencore.moneyharbor.app.entity.Account;
import com.kavencore.moneyharbor.app.entity.User;
import com.kavencore.moneyharbor.app.infrastructure.repository.AccountRepository;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.mock.web.MockHttpServletResponse;
import org.springframework.test.web.servlet.ResultActions;
import org.springframework.test.web.servlet.result.MockMvcResultMatchers;

import java.util.List;
import java.util.Objects;
import java.util.UUID;

import static com.kavencore.moneyharbor.app.infrastructure.service.AccountService.TITLE_SUFFIX;
import static org.assertj.core.api.Assertions.assertThat;
import static com.kavencore.moneyharbor.app.api.v1.controller.AccountsController.ACCOUNTS_PATH;
import static com.kavencore.moneyharbor.app.api.v1.controller.AccountsController.ACCOUNTS_PATH_WITH_SLASH;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@DisplayName("Accounts API — component tests")
class AccountsComponentTest extends AuthenticatedComponentTestBase {

    @Autowired
    protected AccountRepository accountRepository;

    @Test
    @DisplayName("Post /accounts - 201, атрибуты сохранены в базе")
    void createOkMapping() throws Exception {
        String json = AccountJson.CREATE_OK.load();

        MockHttpServletResponse response = performPostAuth(ACCOUNTS_PATH, json)
                .andExpect(status().isCreated())
                .andExpect(MockMvcResultMatchers.header().exists(HttpHeaders.LOCATION))
                .andExpect(MockMvcResultMatchers.jsonPath("$.title").value("Зарплатный"))
                .andExpect(MockMvcResultMatchers.jsonPath("$.currency").value("RUB"))
                .andExpect(MockMvcResultMatchers.jsonPath("$.amount").value(1500.50))
                .andReturn().getResponse();

        UUID id = TestUtils.extractIdFromLocation(response);

        ResultActions resultActions = performGetAuth(ACCOUNTS_PATH_WITH_SLASH + id);
        resultActions.andExpect(status().isOk());
        resultActions.andExpect(MockMvcResultMatchers.jsonPath("$.title").value("Зарплатный"));
        resultActions.andExpect(MockMvcResultMatchers.jsonPath("$.currency").value("RUB"));
        resultActions.andExpect(MockMvcResultMatchers.jsonPath("$.amount").value(1500.50));
    }

    @Test
    @DisplayName("POST без title -> title = {currency}_счет_{number} в БД")
    void createTitleInFirstAccount() throws Exception {
        String json = AccountJson.CREATE_WITHOUT_TITLE_USD.load();

        MockHttpServletResponse response = performPostAuth(ACCOUNTS_PATH, json)
                .andExpect(MockMvcResultMatchers.header().exists(HttpHeaders.LOCATION))
                .andReturn().getResponse();

        UUID id = TestUtils.extractIdFromLocation(response);

        ResultActions resultActions = performGetAuth(ACCOUNTS_PATH_WITH_SLASH + id);

        resultActions.andExpect(MockMvcResultMatchers.jsonPath("$.title").value("USD_счет_1"));
        resultActions.andExpect(MockMvcResultMatchers.jsonPath("$.currency").value("USD"));
        resultActions.andExpect(MockMvcResultMatchers.jsonPath("$.amount").value(0.00));

    }

    @Test
    @DisplayName("POST /accounts: title нового счёта формируется как {валюта}_счет_{max+1}")
    void createAccountWithTitleAutoGeneratedBasedOnExisting() throws Exception {

        assertAccountWithTitleGeneratedCorrectly(
                "RUB",
                AccountJson.CREATE_STANDARD_RUB,
                AccountJson.CREATE_WITHOUT_TITLE_RUB
        );

        assertAccountWithTitleGeneratedCorrectly(
                "USD",
                AccountJson.CREATE_STANDARD_USD,
                AccountJson.CREATE_WITHOUT_TITLE_USD
        );
    }

    private void assertAccountWithTitleGeneratedCorrectly(
            String currency,
            AccountJson baseAccountJson,
            AccountJson newAccountJson) throws Exception {

        final String prefix = currency + TITLE_SUFFIX;

        User user = userRepository.getReferenceById(testUserId);
        checkAndCreateBaseAccount(user, prefix, baseAccountJson);

        List<Account> allAccountsBefore = accountRepository.findAllByUser(user);

        MockHttpServletResponse response = performPostAuth(ACCOUNTS_PATH, newAccountJson.load())
                .andExpect(status().isCreated())
                .andExpect(MockMvcResultMatchers.jsonPath("$.title").isString())
                .andExpect(MockMvcResultMatchers.jsonPath("$.currency").value(currency))
                .andExpect(MockMvcResultMatchers.jsonPath("$.amount").value(0.00))
                .andReturn().getResponse();

        String title = JsonPath.read(response.getContentAsString(), "$.title");

        assertThat(title).as("Title starts with correct prefix for " + currency).startsWith(prefix);
        assertThat(title).as("Title ends with a number for " + currency).matches("^" + prefix + "\\d+$");

        int actualNumber = Integer.parseInt(title.substring(prefix.length()));
        int expectedNumber = calculateExpectedNumber(allAccountsBefore, prefix);
        assertThat(actualNumber)
                .as("Auto-generated title number for " + currency + " is max + 1")
                .isEqualTo(expectedNumber);
    }

    private void checkAndCreateBaseAccount(User user, String currencyPrefix, AccountJson accountJson) throws Exception {
        List<Account> userAccounts = accountRepository.findAllByUser(user);

        boolean exists = userAccounts.stream()
                .map(Account::getTitle)
                .filter(Objects::nonNull)
                .anyMatch(title -> title.startsWith(currencyPrefix));

        if (!exists) {
            performPostAuth(ACCOUNTS_PATH, accountJson.load())
                    .andExpect(status().isCreated());
        }
    }

    /**
     * Вычисляет ожидаемый номер (max + 1) для нового счёта с заданным префиксом.
     *
     * @param accounts Список всех счетов пользователя.
     * @param prefix   Префикс названия счёта (например, "RUB_счет_").
     * @return Ожидаемый номер.
     */
    private int calculateExpectedNumber(List<Account> accounts, String prefix) {
        return accounts.stream()
                .map(Account::getTitle)
                .filter(Objects::nonNull)
                .filter(title -> title.startsWith(prefix))
                .map(title -> title.substring(prefix.length()))
                .mapToInt(s -> {
                    try {
                        return Integer.parseInt(s);
                    } catch (NumberFormatException e) {
                        return 0;
                    }
                })
                .max()
                .orElse(0) + 1;
    }

    @Test
    @DisplayName("DELETE существующего -> 204 и запись удалена")
    void deleteExisting204() throws Exception {
        String json = AccountJson.CREATE_OK.load();
        MockHttpServletResponse resp = performPostAuth(ACCOUNTS_PATH, json)
                .andExpect(status().isCreated())
                .andReturn().getResponse();

        UUID id = TestUtils.extractIdFromLocation(resp);

        performDeleteAuthOk(ACCOUNTS_PATH_WITH_SLASH + id)
                .andExpect(result -> {
                    int s = result.getResponse().getStatus();
                    if (s != HttpStatus.NO_CONTENT.value() && s != HttpStatus.OK.value()) {
                        throw new AssertionError("Expected 200 or 204, got " + s);
                    }
                });

        performGetAuth(ACCOUNTS_PATH_WITH_SLASH + id)
                .andExpect(status().isNotFound());
    }


    @Test
    @DisplayName("DELETE несуществующего -> 200 (идемпотентно)")
    void deleteAbsent200() throws Exception {
        UUID randomId = UUID.randomUUID();
        performGetAuth(ACCOUNTS_PATH_WITH_SLASH + randomId)
                .andExpect(status().isNotFound());

        performDeleteAuthOk(ACCOUNTS_PATH_WITH_SLASH + randomId)
                .andExpect(result -> Assertions.assertThat(result.getResponse().getStatus()).isEqualTo(200));
    }

    @Test
    @DisplayName("GET несуществующего -> 404 ProblemDetail")
    void getAbsent404() throws Exception {
        UUID missing = UUID.randomUUID();
        performGetAuth(ACCOUNTS_PATH_WITH_SLASH + missing)
                .andExpect(status().isNotFound())
                .andExpect(MockMvcResultMatchers.content().contentTypeCompatibleWith(MediaType.APPLICATION_PROBLEM_JSON_VALUE))
                .andExpect(MockMvcResultMatchers.jsonPath("$.title").value(HttpStatus.NOT_FOUND.getReasonPhrase()))
                .andExpect(MockMvcResultMatchers.jsonPath("$.detail").value("Account not found: " + missing));
    }

    @Test
    @DisplayName("POST с невалидным телом (неизвестный enum) -> 400 ProblemDetail")
    void postInvalidJson400() throws Exception {
        String badJson = AccountJson.CREATE_INVALID_ENUM.load();

        performPostAuth(ACCOUNTS_PATH, badJson)
                .andExpect(status().isBadRequest())
                .andExpect(MockMvcResultMatchers.content().contentTypeCompatibleWith(MediaType.APPLICATION_PROBLEM_JSON_VALUE))
                .andExpect(MockMvcResultMatchers.jsonPath("$.title").value(HttpStatus.BAD_REQUEST.getReasonPhrase()))
                .andExpect(MockMvcResultMatchers.jsonPath("$.detail").value("Invalid value in request body"));
    }

    @Test
    @DisplayName("GET /accounts/{id} с невалидным UUID -> 400 ProblemDetail")
    void getInvalidUuid400() throws Exception {
        performGetAuth(ACCOUNTS_PATH_WITH_SLASH + "abc")
                .andExpect(status().isBadRequest())
                .andExpect(MockMvcResultMatchers.content().contentTypeCompatibleWith(MediaType.APPLICATION_PROBLEM_JSON_VALUE))
                .andExpect(MockMvcResultMatchers.jsonPath("$.title").value(HttpStatus.BAD_REQUEST.getReasonPhrase()))
                .andExpect(MockMvcResultMatchers.jsonPath("$.detail").value("Invalid UUID in path parameter 'id'"));
    }

    @Test
    @DisplayName("DELETE /accounts/{id} с невалидным UUID -> 400 ProblemDetail")
    void deleteInvalidUuid400() throws Exception {
        performDeleteAuthOk(ACCOUNTS_PATH_WITH_SLASH + "abc")
                .andExpect(status().isBadRequest())
                .andExpect(MockMvcResultMatchers.content().contentTypeCompatibleWith(MediaType.APPLICATION_PROBLEM_JSON_VALUE))
                .andExpect(MockMvcResultMatchers.jsonPath("$.title").value(HttpStatus.BAD_REQUEST.getReasonPhrase()))
                .andExpect(MockMvcResultMatchers.jsonPath("$.detail").value("Invalid UUID in path parameter 'id'"));
    }

    @Test
    @DisplayName("POST: currency не из enum -> 400 ProblemDetail (HttpMessageNotReadable)")
    void postCurrencyNotInEnum400() throws Exception {
        String json = AccountJson.CREATE_WITH_CURRENCY_NOT_IN_ENUM.load();

        performPostAuth(ACCOUNTS_PATH, json)
                .andExpect(status().isBadRequest())
                .andExpect(MockMvcResultMatchers.content().contentTypeCompatibleWith(MediaType.APPLICATION_PROBLEM_JSON_VALUE))
                .andExpect(MockMvcResultMatchers.jsonPath("$.title").value(HttpStatus.BAD_REQUEST.getReasonPhrase()))
                .andExpect(MockMvcResultMatchers.jsonPath("$.detail").value("Invalid value in request body"));
    }

    @Test
    @DisplayName("POST: не передано обязательное поле currency -> 400 ProblemDetail (Bean Validation)")
    void postMissingCurrency400() throws Exception {
        String json = AccountJson.CREATE_MISSING_CURRENCY.load();

        performPostAuth(ACCOUNTS_PATH, json)
                .andExpect(status().isBadRequest())
                .andExpect(MockMvcResultMatchers.content().contentTypeCompatibleWith(MediaType.APPLICATION_PROBLEM_JSON_VALUE))
                .andExpect(MockMvcResultMatchers.jsonPath("$.title").value(HttpStatus.BAD_REQUEST.getReasonPhrase()))
                .andExpect(MockMvcResultMatchers.jsonPath("$.errors[0]").value(org.hamcrest.Matchers.containsString("currency")));
    }

    @Test
    @DisplayName("POST: amount scale != 2 -> 400 ProblemDetail (Bean Validation)")
    void postAmountScale3_400() throws Exception {
        String json = AccountJson.CREATE_AMOUNT_SCALE_3.load();

        performPostAuth(ACCOUNTS_PATH, json)
                .andExpect(status().isBadRequest())
                .andExpect(MockMvcResultMatchers.content().contentTypeCompatibleWith(MediaType.APPLICATION_PROBLEM_JSON_VALUE))
                .andExpect(MockMvcResultMatchers.jsonPath("$.title").value(HttpStatus.BAD_REQUEST.getReasonPhrase()))
                .andExpect(MockMvcResultMatchers.jsonPath("$.errors[0]").value(org.hamcrest.Matchers.containsString("amount")));
    }

    @Test
    @DisplayName("POST: amount integer digits > 17 (для NUMERIC(19,2)) -> 400 ProblemDetail (Bean Validation)")
    void postAmountIntegerTooLong400() throws Exception {
        String json = AccountJson.CREATE_AMOUNT_INTEGER_TOO_LONG.load();

        performPostAuth(ACCOUNTS_PATH, json)
                .andExpect(status().isBadRequest())
                .andExpect(MockMvcResultMatchers.content().contentTypeCompatibleWith(MediaType.APPLICATION_PROBLEM_JSON_VALUE))
                .andExpect(MockMvcResultMatchers.jsonPath("$.title").value(HttpStatus.BAD_REQUEST.getReasonPhrase()))
                .andExpect(MockMvcResultMatchers.jsonPath("$.errors[0]").value(org.hamcrest.Matchers.containsString("amount")));
    }

    @Test
    @DisplayName("POST: title некорректного типа -> 400 ProblemDetail (HttpMessageNotReadable)")
    void postTitleWrongType400() throws Exception {
        String json = AccountJson.CREATE_TITLE_WRONG_TYPE.load();

        performPostAuth(ACCOUNTS_PATH, json)
                .andExpect(status().isBadRequest())
                .andExpect(MockMvcResultMatchers.content().contentTypeCompatibleWith(MediaType.APPLICATION_PROBLEM_JSON_VALUE))
                .andExpect(MockMvcResultMatchers.jsonPath("$.title").value(HttpStatus.BAD_REQUEST.getReasonPhrase()))
                .andExpect(MockMvcResultMatchers.jsonPath("$.detail").value("Invalid value in request body"));
    }

    @Test
    @DisplayName("POST /accounts без авторизации -> 401 Unauthorized")
    void createWithoutAuth401() throws Exception {
        String json = AccountJson.CREATE_OK.load();

        performPostNoAuth(ACCOUNTS_PATH, json)
                .andExpect(status().isUnauthorized())
                .andExpect(MockMvcResultMatchers.header().doesNotExist(HttpHeaders.LOCATION));
    }

    @Test
    @DisplayName("POST: title максимальной длины из OpenAPI, maxLength = 50 -> 201")
    void createAccount_WhenTitleMaxLengthFromOpenApi_ShouldSucceed() throws Exception {

        performPostAuth(ACCOUNTS_PATH, AccountJson.CREATE_TITLE_VALIDATE_LENGTH.load())
                .andExpect(status().isCreated())
                .andExpect(MockMvcResultMatchers.jsonPath("$.title").value("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
                .andExpect(MockMvcResultMatchers.jsonPath("$.currency").value("RUB"))
                .andExpect(MockMvcResultMatchers.jsonPath("$.amount").value(0.00));

    }

    @Test
    @DisplayName("POST с title превышающим максимум из OpenAPI, maxLength = 51 -> 400")
    void createAccount_WhenTitleExceedsMaxLengthFromOpenApi_ShouldFail() throws Exception {

        performPostAuth(ACCOUNTS_PATH, AccountJson.CREATE_TITLE_INVALIDATE_LENGTH.load())
                .andExpect(status().isBadRequest())
                .andExpect(MockMvcResultMatchers.content().contentTypeCompatibleWith(MediaType.APPLICATION_PROBLEM_JSON_VALUE))
                .andExpect(MockMvcResultMatchers.jsonPath("$.title").value(HttpStatus.BAD_REQUEST.getReasonPhrase()))
                .andExpect(MockMvcResultMatchers.jsonPath("$.errors[0]").value("title: size must be between 0 and 50"));
    }


    @Test
    @DisplayName("POST /accounts - 409: title+currency уже заняты -> ProblemDetail")
    void postDuplicateTitleSameCurrency409() throws Exception {
        performPostAuth(ACCOUNTS_PATH, AccountJson.CREATE_DUPLICATE_TITLE_RUB.load())
                .andExpect(status().isCreated());

        performPostAuth(ACCOUNTS_PATH, AccountJson.CREATE_DUPLICATE_TITLE_RUB.load())
                .andExpect(status().isConflict())
                .andExpect(MockMvcResultMatchers.content().contentTypeCompatibleWith(MediaType.APPLICATION_PROBLEM_JSON_VALUE))
                .andExpect(MockMvcResultMatchers.jsonPath("$.title").value("SHARED_ACCOUNT"))
                .andExpect(MockMvcResultMatchers.jsonPath("$.detail")
                        .value("Account with title 'SHARED_ACCOUNT' already exists for currency 'RUB'"))
                .andExpect(MockMvcResultMatchers.jsonPath("$.instruction")
                        .value("Create an account with a unique title"));
    }

    @Test
    @DisplayName("POST /accounts - 201: одинаковый title, другая currency")
    void postDuplicateTitleDifferentCurrency201() throws Exception {
        performPostAuth(ACCOUNTS_PATH, AccountJson.CREATE_DUPLICATE_TITLE_RUB.load())
                .andExpect(status().isCreated());

        performPostAuth(ACCOUNTS_PATH, AccountJson.CREATE_DUPLICATE_TITLE_USD.load())
                .andExpect(status().isCreated())
                .andExpect(MockMvcResultMatchers.jsonPath("$.title").value("SHARED_ACCOUNT"))
                .andExpect(MockMvcResultMatchers.jsonPath("$.currency").value("USD"));
    }
}