name: CI

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (assemble all, skip tests)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Setup Java 21 + Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Gradle assemble (skip tests)
        run: ./gradlew assemble -x test --no-daemon


  tests:
    name: Run all tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant permession for gradlew
        run: chmod +x ./gradlew

      - name: Setup Java 21 + Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Pre-pull postgres image
        run: docker pull postgres:16-alpine || true

      - name: Gradle test(all modules)
        run: ./gradlew test --no-daemon

      - name: Uploads test reports (all modules)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-reports
          path: "**/build/reports/tests/test/**"
