name: CI

on:
  push:
  workflow_dispatch:
    inputs:
      failOnCVSS:
        description: "Fail if CVSS >= (0..10). Recommended: 7"
        required: false
        default: "7"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (assemble all, skip tests)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Setup Java 21 + Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Gradle assemble (skip tests)
        run: ./gradlew assemble -x test --no-daemon


  tests:
    name: Gradle test (all modules)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant permession for gradlew
        run: chmod +x ./gradlew

      - name: Setup Java 21 + Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Pre-pull postgres image
        run: docker pull postgres:16-alpine || true

      - name: Gradle test(all modules)
        run: ./gradlew test --no-daemon

      - name: Upload test reports (all modules)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-reports
          path: "**/build/reports/tests/test/**"

  depcheck_manual:
    name: Dependency scan (manual)
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check (fail on CVSS threshold)
        uses: dependency-check/Dependency-Check_Action@main
        id: depcheck
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: "moneyharbor"
          path: "."
          format: "HTML"
          out: "reports"
          args: >
            --failOnCVSS ${{ github.event.inputs.failOnCVSS }}

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html

